### ISSUE TITLE
Error on  npm install multi-hashing

### ISSUE THREAD

**Issue by ooonyx** [krisklosterman/node-multi-hashing#2]
Server UBUNTU 17.04

Error after execute npm install multi-hashing, my npm version is the last one.

multihashing.target.mk:113: recipe for target 'Release/obj.target/multihashing/multihashing.o' failed
make: *** [Release/obj.target/multihashing/multihashing.o] Error 1
make: Leaving directory '/home/userx/node_modules/multi-hashing/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
gyp ERR! System Linux 4.10.0-32-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/userx/node_modules/multi-hashing
gyp ERR! node -v v4.7.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/home/userx/package.json'
npm WARN userx No description
npm WARN userx No repository field.
npm WARN userx No README data
npm WARN userx No license field.
npm ERR! Linux 4.10.0-32-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "multi-hashing"
npm ERR! node v4.7.2
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! multi-hashing@0.0.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the multi-hashing@0.0.4 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the multi-hashing package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs multi-hashing
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls multi-hashing
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/userx/npm-debug.log

**Comment by krisklosterman** [comment]
Sounds like an issue with npm or node-gyp install, and not node-multi-hashing

npm WARN enoent ENOENT: no such file or directory, open '/home/userx/package.json'

**Comment by ooonyx** [comment]
I verified that  package.json file´s located in unomp folder, so.. I execute sudo npm install multi-hashing inside this folder but error occured again:

make: *** [Release/obj.target/multihashing/multihashing.o] Error 1
make: Leaving directory '/home/userx/unomp/node_modules/multi-hashing/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
gyp ERR! System Linux 4.10.0-32-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/userx/unomp/node_modules/multi-hashing
gyp ERR! node -v v4.7.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
unified-node-open-mining-portal@1.0.0 /home/userx/unomp
├── node.bittrex.api@0.5.1  extraneous (git://github.com/n0mad01/node.bittrex.api.git#25bb15df8b51c24c9549c395554e8912306ebea3)
└── poloniex.js@0.0.5  extraneous (git://github.com/sigwo/poloniex.js.git#9f2651b6ab282936cada4814464f3d9251457215)

npm ERR! Linux 4.10.0-32-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "multi-hashing"
npm ERR! node v4.7.2
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! multi-hashing@0.0.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the multi-hashing@0.0.4 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the multi-hashing package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs multi-hashing
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls multi-hashing
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/userx/unomp/npm-debug.log

**Comment by krisklosterman** [comment]
```
npm ERR! node v4.7.2
npm ERR! npm v3.5.2
```

Please use node version 8.x+ @ooonyx
